// Abblix OIDC Server Library
// SPDX-FileCopyrightText: Copyright (c) Abblix LLP
// SPDX-License-Identifier: LicenseRef-Abblix-EULA
//
// This software is provided 'as-is', without any express or implied warranty.
// Licensing terms, including free-of-charge use, are stated in LICENSE.md
// in the official repository at https://github.com/Abblix/Oidc.Server

using Abblix.Oidc.Server.Common;
using Abblix.Oidc.Server.Features.ClientInformation;
using Abblix.Oidc.Server.Features.UserAuthentication;

namespace Abblix.Oidc.Server.Features.Tokens;

/// <summary>
/// Issues OpenID Connect ID Tokens (OIDC Core section 2 and section 3.1.3.6) for authenticated end-users,
/// embedding the standard claims of OIDC Core section 5.1, the client's nonce, and where applicable
/// the <c>c_hash</c>/<c>at_hash</c> binding claims (OIDC Core section 3.1.3.6 and section 3.2.2.10) that tie
/// the ID Token to a co-issued authorization code or access token.
/// </summary>
public interface IIdentityTokenService
{
	/// <summary>
	/// Asynchronously generates a new identity token based on the provided authentication session, authorization
	/// context, client information, and optionally includes `c_hash` or `at_hash` claims when an authorization code or
	/// access token is provided. These claims are used for validating the hash of the authorization code and
	/// access token respectively, enhancing the security of token exchange in OAuth 2.0 flows.
	/// </summary>
    /// <param name="authSession">The authentication session, which includes details such as the user's unique
    /// identifier and the session's authentication time.</param>
    /// <param name="authContext">The authorization context, providing contextual information about the authorization
    /// request, such as the requested scopes and additional claims to be included in the identity token.</param>
    /// <param name="clientInfo">Detailed information about the client that is requesting the identity token, including
    /// its identifier and specific requirements for the token.</param>
    /// <param name="includeUserClaims">A boolean value indicating whether claims about the user should be included
    /// in the identity token. When set to <c>true</c>, the token will include claims based on the requested scopes
    /// and additional specified claims.</param>
    /// <param name="authorizationCode">An optional authorization code provided to include the `c_hash` claim in the
    /// identity token, which is a hash of the code. This parameter is typically used in authorization code flow.
    /// </param>
    /// <param name="accessToken">An optional access token provided to include the `at_hash` claim in the identity token,
    /// which is a hash of the token. This parameter is used when the identity token is issued alongside an access token.
    /// </param>
    /// <param name="pushBindings">The CIBA push notification this token travels in, or
    /// <see langword="null"/> when it does not. Non-null adds the two bindings Section 10.3.1 requires
    /// there and nowhere else - the request identifier verbatim, and the refresh token's hash when one
    /// is sent.</param>
    /// <returns>A task that, upon completion, yields an <see cref="EncodedJsonWebToken"/> that represents the newly
    /// generated identity token, encoded and ready for transmission to the client.</returns>
    /// <remarks>
    /// Identity tokens generated by this service adhere to the OpenID Connect standard, ensuring that they can be used
    /// reliably in identity assertions across different clients and services that support OpenID Connect.
    /// </remarks>
	Task<EncodedJsonWebToken?> CreateIdentityTokenAsync(
		AuthSession authSession,
		AuthorizationContext authContext,
		ClientInfo clientInfo,
		bool includeUserClaims,
		string? authorizationCode,
		string? accessToken,
		PushDeliveryBindings? pushBindings = null);
}
