// Abblix OpenID Connect Server Library
// Copyright (c) 2024 by Abblix LLP
// 
// This software is provided 'as-is', without any express or implied warranty. In no
// event will the authors be held liable for any damages arising from the use of this
// software.
// 
// Permitted Use: This software is open for use and extension by non-profit,
// educational and community projects under the condition that it remains unmodified
// and used in its entirety through official Nuget packages. Any unauthorized
// modification, forking of the whole repository, or altering individual files is
// strictly prohibited to ensure development occurs solely within the official Abblix LLP
// repository.
// 
// Prohibited Actions: Redistribution, modification, incorporation of this software or
// any part thereof into other products, and creation of derivative works are not
// permitted without obtaining a commercial license from Abblix LLP.
// 
// Commercial Use: A separate license is required for commercial use, including
// functionalities extended beyond the original software. For information on obtaining
// a commercial license, please contact Abblix LLP.
// 
// Enforcement: Unauthorized redistribution, modification, or use of this software in
// other projects or products is strictly prohibited without prior written permission
// from the copyright holder. Violations may be subject to legal action.
// 
// For more information, please refer to the license agreement located at:
// https://github.com/Abblix/Oidc.Server/blob/master/README.md

using Abblix.Oidc.Server.Common;
using Abblix.Oidc.Server.Features.ClientInformation;
using Abblix.Oidc.Server.Features.UserAuthentication;

namespace Abblix.Oidc.Server.Features.Tokens;

/// <summary>
/// Provides functionality for creating and managing identity tokens as part of OpenID Connect authentication processes.
/// This service is responsible for generating identity tokens that encapsulate the authenticated user's identity
/// information and any additional claims or information authorized for release to the requesting client application.
/// </summary>
public interface IIdentityTokenService
{
	/// <summary>
	/// Asynchronously generates a new identity token based on the provided authentication session, authorization
	/// context, client information, and optionally includes `c_hash` or `at_hash` claims when an authorization code or
	/// access token is provided. These claims are used for validating the hash of the authorization code and
	/// access token respectively, enhancing the security of token exchange in OAuth 2.0 flows.
	/// </summary>
    /// <param name="authSession">The authentication session, which includes details such as the user's unique
    /// identifier and the session's authentication time.</param>
    /// <param name="authContext">The authorization context, providing contextual information about the authorization
    /// request, such as the requested scopes and additional claims to be included in the identity token.</param>
    /// <param name="clientInfo">Detailed information about the client that is requesting the identity token, including
    /// its identifier and specific requirements for the token.</param>
    /// <param name="includeUserClaims">A boolean value indicating whether claims about the user should be included
    /// in the identity token. When set to <c>true</c>, the token will include claims based on the requested scopes
    /// and additional specified claims.</param>
    /// <param name="authorizationCode">An optional authorization code provided to include the `c_hash` claim in the
    /// identity token, which is a hash of the code. This parameter is typically used in authorization code flow.
    /// </param>
    /// <param name="accessToken">An optional access token provided to include the `at_hash` claim in the identity token,
    /// which is a hash of the token. This parameter is used when the identity token is issued alongside an access token.
    /// </param>
    /// <returns>A task that, upon completion, yields an <see cref="EncodedJsonWebToken"/> that represents the newly
    /// generated identity token, encoded and ready for transmission to the client.</returns>
    /// <remarks>
    /// Identity tokens generated by this service adhere to the OpenID Connect standard, ensuring that they can be used
    /// reliably in identity assertions across different clients and services that support OpenID Connect.
    /// </remarks>
	Task<EncodedJsonWebToken> CreateIdentityTokenAsync(
		AuthSession authSession,
		AuthorizationContext authContext,
		ClientInfo clientInfo,
		bool includeUserClaims,
		string? authorizationCode,
		string? accessToken);
}
