// Abblix OIDC Server Library
// SPDX-FileCopyrightText: Copyright (c) Abblix LLP
// SPDX-License-Identifier: LicenseRef-Abblix-EULA
//
// This software is provided 'as-is', without any express or implied warranty.
// Licensing terms, including free-of-charge use, are stated in LICENSE.md
// in the official repository at https://github.com/Abblix/Oidc.Server

using Abblix.Oidc.Server.Endpoints.CheckSession.Interfaces;
using Abblix.Oidc.Server.Mvc.Formatters.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Abblix.Oidc.Server.Mvc.Features.SessionManagement;

/// <summary>
/// A decorator class that adds caching functionality to the Check Session response formatting process.
/// </summary>
/// <param name="inner">The inner Check Session response formatter.</param>
/// <param name="cache">The cache used to store formatted responses.</param>
public class CheckSessionResponseCachingDecorator(
    ICheckSessionResponseFormatter inner,
    ICheckSessionResponseCache cache): ICheckSessionResponseFormatter
{
    /// <summary>
    /// Formats a Check Session response and caches the formatted result using the provided response's cache key.
    /// </summary>
    /// <param name="response">The Check Session response to be formatted.</param>
    /// <returns>
    /// A <see cref="Task{TResult}"/> representing the asynchronous operation. The task result contains
    /// the formatted ActionResult, either retrieved from the cache or generated by the inner formatter.
    /// </returns>
    public Task<ActionResult> FormatResponseAsync(CheckSessionResponse response)
        => cache.GetOrAddAsync(response.CacheKey, () => inner.FormatResponseAsync(response));
}
