// Abblix OIDC Client Library
// Copyright (c) Abblix LLP. All rights reserved.
//
// DISCLAIMER: This software is provided 'as-is', without any express or implied
// warranty. Use at your own risk. Abblix LLP is not liable for any damages
// arising from the use of this software.
//
// LICENSE RESTRICTIONS: This code may not be modified, copied, or redistributed
// in any form outside of the official GitHub repository at:
// https://github.com/Abblix/OIDC.Server. All development and modifications
// must occur within the official repository and are managed solely by Abblix LLP.
//
// Unauthorized use, modification, or distribution of this software is strictly
// prohibited and may be subject to legal action.
//
// For full licensing terms, please visit:
//
// https://oidc.abblix.com/license
//
// CONTACT: For license inquiries or permissions, contact Abblix LLP at
// info@abblix.com

using System.Security.Cryptography;
using System.Text;
using Abblix.Jwt;
using Abblix.Oidc.Client.Features.Authorization.Requests;
using Abblix.Oidc.Client.Features.ClientKeys;
using Abblix.Oidc.Server.Common.Constants;
using Abblix.Oidc.Server.Features.ClientInformation;
using Microsoft.Extensions.DependencyInjection;

namespace Abblix.Oidc.Client.E2E.Tests;

/// <summary>
/// An ID Token the provider encrypted to this client, opened by this client.
/// </summary>
/// <remarks>
/// The token arrives as a JWE wrapping the signed one, so nothing about it can be read - not the issuer, not
/// the audience, not the signature - until it has been decrypted with a key only this client holds. That
/// makes it the one case where the whole validation chain depends on a step this suite could not exercise at
/// all before: a client holding no keys refuses the token before any of the thirteen checks are reached.
/// The provider here is the real one, configured to encrypt the way a provider would be, and the key pair is
/// generated by the test so the private half exists nowhere else.
/// </remarks>
public class EncryptedIdentityTokenTests : IAsyncLifetime
{
    private const string ClientId = "e2e-encrypted-id-token";
    private const string Subject = "e2e-subject";

    private readonly ClientAgainstServerFixture _fixture = new();

    /// <summary>
    /// The client's key pair. The private half exists only here, so a token the provider encrypts can be
    /// opened by nothing else in the test.
    /// </summary>
    private readonly JsonWebKey _encryptionKey = JsonWebKeyFactory.CreateEllipticCurve(
        EllipticCurveTypes.P256, SigningAlgorithms.ES256) with
    {
        Usage = PublicKeyUsages.Encryption,

        // The registered id_token_encrypted_response_alg decides the key management algorithm; the key
        // itself pins none.
        Algorithm = null,
    };

    public async ValueTask InitializeAsync()
    {
        _fixture.ConfigureProviderServices = services =>
            services.PostConfigure<Abblix.Oidc.Server.Common.Configuration.OidcOptions>(options =>
                options.Clients =
                [
                    ..options.Clients,
                    new ClientInfo(ClientId)
                    {
                        ClientSecrets =
                        [
                            new ClientSecret
                            {
                                Sha512Hash = SHA512.HashData(
                                    Encoding.UTF8.GetBytes(ClientAgainstServerFixture.ClientSecret)),
                            },
                        ],
                        TokenEndpointAuthMethod = ClientAuthenticationMethods.ClientSecretPost,
                        RedirectUris = [new Uri(ClientAgainstServerFixture.RedirectUri)],

                        // The public half, exactly as a client publishes it. The provider encrypts to this
                        // and can never read what it produced.
                        Jwks = new JsonWebKeySet([_encryptionKey.Sanitize(includePrivateKeys: false)]),
                        IdentityTokenEncryptedResponseAlgorithm =
                            EncryptionAlgorithms.KeyManagement.EcdhEsAes256KW,
                        // The fixture asks for offline_access, as a signed-in application would.
                        OfflineAccessAllowed = true,
                        IdentityTokenEncryptedResponseEncryption =
                            EncryptionAlgorithms.ContentEncryption.Aes128CbcHmacSha256,
                    },
                ]);

        await _fixture.InitializeAsync();
    }

    public async ValueTask DisposeAsync() => await _fixture.DisposeAsync();

    /// <summary>
    /// Builds the client, optionally holding the private half.
    /// </summary>
    private ServiceProvider CreateClient(bool withDecryptionKey)
    {
        _fixture.ConfigureClientServices = withDecryptionKey
            ? services => services.AddClientDecryptionKeys([_encryptionKey])
            : null;

        return _fixture.CreateOidcClient(clientId: ClientId);
    }

    private async Task<IReadOnlyDictionary<string, IReadOnlyList<string>>> AuthorizeAsync(
        ServiceProvider client, CancellationToken cancellationToken)
    {
        var request = await client.GetRequiredService<IAuthorizationRequestBuilder>()
            .CreateAsync(new Uri("/home", UriKind.Relative), cancellationToken: cancellationToken);

        using var browser = _fixture.CreateBrowser();
        using var response = await browser.GetAsync(request.RequestUri, cancellationToken);

        return ClientHostFixture.QueryOf(ClientHostFixture.RedirectOf(response));
    }

    /// <summary>
    /// Holding the key, the client opens the token and signs the user in.
    /// </summary>
    [Fact]
    public async Task AClientHoldingTheKeyReadsTheToken()
    {
        var cancellationToken = TestContext.Current.CancellationToken;
        await using var client = CreateClient(withDecryptionKey: true);

        var callback = await AuthorizeAsync(client, cancellationToken);

        var signIn = await client.GetRequiredService<IOidcClient>()
            .HandleCallbackAsync(callback, cancellationToken);

        Assert.Equal(Subject, signIn.Principal.Identity?.Name);
        Assert.Equal(ClientAgainstServerFixture.Issuer, signIn.IdentityToken.Payload.Issuer);
    }

    /// <summary>
    /// The token really was encrypted, rather than the provider quietly sending a plain one.
    /// </summary>
    /// <remarks>
    /// Without this the case above would pass just as well against a provider that ignored the request to
    /// encrypt, and would then be proving nothing about decryption at all. A JWE has five parts to a JWS's
    /// three (RFC 7516 section 3.1).
    /// </remarks>
    [Fact]
    public async Task TheTokenArrivesEncrypted()
    {
        var cancellationToken = TestContext.Current.CancellationToken;
        await using var client = CreateClient(withDecryptionKey: true);

        var callback = await AuthorizeAsync(client, cancellationToken);

        var signIn = await client.GetRequiredService<IOidcClient>()
            .HandleCallbackAsync(callback, cancellationToken);

        Assert.Equal(5, signIn.EncodedIdentityToken.Split('.').Length);
    }

    /// <summary>
    /// Without the key the client refuses the token rather than reading anything out of it.
    /// </summary>
    /// <remarks>
    /// This is what a client registered for encryption but deployed without its keys looks like, and the
    /// answer has to be a refusal: nothing inside the token is readable, so there is no partial result to
    /// fall back on.
    /// </remarks>
    [Fact]
    public async Task AClientWithoutTheKeyRefusesTheToken()
    {
        var cancellationToken = TestContext.Current.CancellationToken;
        await using var client = CreateClient(withDecryptionKey: false);

        var callback = await AuthorizeAsync(client, cancellationToken);

        await Assert.ThrowsAnyAsync<Exception>(
            () => client.GetRequiredService<IOidcClient>().HandleCallbackAsync(callback, cancellationToken));
    }
}
