// Abblix OIDC Server Library
// SPDX-FileCopyrightText: Copyright (c) Abblix LLP
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0. You may obtain a copy at
// http://www.apache.org/licenses/LICENSE-2.0

using Xunit;

namespace Abblix.Analyzers.UnitTests;

/// <summary>
/// An expression joining more than three conditions with <c>&amp;&amp;</c>, <c>||</c> and <c>?:</c> is refused; the
/// cases a pattern lists with <c>or</c> and <c>and</c> are not conditions, and a lambda, an arm or an argument is
/// judged apart.
/// </summary>
public class ExpressionComplexityAnalyzerTests
{
    [Theory]
    [InlineData("bool M(bool a, bool b, bool c, bool d, bool e) => a && b || c && d || e;")]
    [InlineData("int M(bool a, bool b, bool c, bool d) => a ? b ? 1 : 2 : c && d ? 3 : 4;")]
    [InlineData("bool M(bool a, bool b, bool c, bool d, bool e) { var x = (a && b) || (c && (d || e)); return x; }")]
    public async Task FourConditionalOperatorsAreReported(string member)
    {
        var diagnostic = Assert.Single(await AnalyzerRun.DiagnosticsOf(new ExpressionComplexityAnalyzer(), Around(member)));

        Assert.Equal(ExpressionComplexityAnalyzer.Rule.Id, diagnostic.Id);
    }

    [Theory]
    [InlineData("bool M(bool a, bool b, bool c, bool d) => a && b || c && d;")]
    [InlineData("bool M(object o) => o switch { int or long or short or byte or sbyte => true, _ => false };")]
    [InlineData("bool M(object o) => o is int or long or short or byte or sbyte;")]
    [InlineData("bool M(int i) => i is > 0 and < 10 or > 20 and < 30 or 42;")]
    public async Task ThreeOperatorsAndPatternListsAreNotReported(string member)
        => Assert.Empty(await AnalyzerRun.DiagnosticsOf(new ExpressionComplexityAnalyzer(), Around(member)));

    /// <summary>Each arm, each argument and each lambda body is read on its own.</summary>
    [Theory]
    [InlineData("int M(bool a, bool b, bool c, bool d) => (a && b) switch { true when c && d => 1, _ => a && c ? 2 : 3 };")]
    [InlineData("bool M(bool a, bool b, bool c, bool d) => N(a && b && c, b || c || d);")]
    [InlineData("(bool, bool, bool, bool) M(bool a, bool b) => (a && b, a || b, a ? b : a, b && a);")]
    [InlineData("int M(bool a, bool b) => (a && b) switch { true when a && b => 1, false when a || b => 2, _ => b && a ? 3 : 4 };")]
    [InlineData("System.Func<bool, bool> M(bool a, bool b, bool c) => a && b ? x => x && a && b && c : x => x;")]
    [InlineData("P M(bool a, bool b) => new P { X = a ? 1 : 0, Y = b ? 1 : 0, Z = a && b ? 1 : 0 };")]
    [InlineData("P M(P p, bool a, bool b) => p with { X = a ? 1 : 0, Y = b ? 1 : 0, Z = a && b ? 1 : 0 };")]
    public async Task PartsJudgedApartAreNotSummed(string member)
        => Assert.Empty(await AnalyzerRun.DiagnosticsOf(new ExpressionComplexityAnalyzer(), Around(member)));

    /// <summary>A lambda over the ceiling is reported at its body, and the expression holding it stays silent.</summary>
    [Fact]
    public async Task LambdaBodyOverCeilingIsReportedOnce()
    {
        const string body = "x && a && b && c || a";
        var source = Around("System.Func<bool, bool>? M(bool a, bool b, bool c) => a && b ? x => " + body + " : null;");

        var diagnostic = Assert.Single(await AnalyzerRun.DiagnosticsOf(new ExpressionComplexityAnalyzer(), source));

        Assert.Equal(ExpressionComplexityAnalyzer.Rule.Id, diagnostic.Id);
        Assert.Equal(body, source.Substring(diagnostic.Location.SourceSpan.Start, diagnostic.Location.SourceSpan.Length));
    }

    /// <summary>
    /// Generated code keeps whatever its generator wrote: nobody reads or edits that output.
    /// </summary>
    [Theory]
    [InlineData("Model.g.cs", "class C { bool M(bool a, bool b, bool c, bool d, bool e) => a && b || c && d || e; }")]
    [InlineData("Model.cs", "// <auto-generated/>\nclass C { bool M(bool a, bool b, bool c, bool d, bool e) => a && b || c && d || e; }")]
    public async Task GeneratedCodeIsNotReported(string path, string source)
        => Assert.Empty(await AnalyzerRun.DiagnosticsOf(new ExpressionComplexityAnalyzer(), (path, source)));

    private static string Around(string member)
        => "#nullable enable\n" +
           "record P { public int X { get; init; } public int Y { get; init; } public int Z { get; init; } }\n" +
           "class C\n{\n    " + member + "\n    static bool N(bool x, bool y) => x;\n}\n";
}
