name: CodeQL

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '0 0 * * 1' # Weekly schedule at midnight UTC on Mondays

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Increase the timeout limit as needed
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      matrix:
        language: [ 'javascript', 'typescript', 'csharp', 'html', 'css' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
